default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5
  template: template0

development:
  <<: *default
  database: money_tracker_development

test:
  <<: *default
  database: money_tracker_test

staging:
  <<: *default
  database: money_tracker_staging

production:
  <<: *default
  database: money_tracker_production
